/*
	SELECT -> RETREIVE DATA FROM DATABASE
	
	1. SELECT * FROM CAPE;

	2. SELECT ROLL, NAME, DOB FROM CAPE;

	USAGE OF DISTINCT KEYWORD

	3. SELECT DISTINCT COURSE FROM CAPE;

	USAGE OF COUNT FROM CAPE

	4. SELECT COUNT(DISTINCT COURSE) FROM CAPE;

	AS KEYWORD

	5. USAGE OF AS KEYWORD

	WHERE CLAUSE

	6. SELECT NAME, ROLL, DOB WHERE COLLEGE = 'KTR';

	OPERATORS >, <, >=, <=, != AND, BETWEEN, LIKE, IN
	
	AND WORKS WHEN BOTH THE CONDITIONS ARE TRUE

	OR WORKS WHEN ONE OF THE CONDITION IS TRUE

	LIKE IS WILDCARD TO LOOK FOR SOME PATTERN

	Q: EVERY NAME WICH CONTAINS THE LETTER T
	A: SELECT NAME FROM CAPE WHERE NAME LIKE '%T%'
	   %T% MEANS ANYTHING BEFORE T AND ANYTHING AFTER T
	   ANYTHING MEANS ANY NUMBER OF CHARACTERS AND ANY CHARACTER

	IN KEYWORD: ALLOWS U TO CHOOSE MULTIPLE VALUES

	SELECT NAME, ROLL FROM CAPE WHERE COURSE NOT IN ('CSE');

	ORDER BY ASC OR ORDER BY DESC
	NOTE 1: ORDER BY CAN ACCEPT MULTIPLE COLUMNS
	SIMILAR TO THE FACT THAT IF 2 VALUES ARE EQUAL
	THEN WHICH VALUE TO BE KEPT FIRST
	NOTE 2: ORDER BY NAME ASC, ROLL DESC

	SELECT * FROM CAPE ORDER BY NAME DESC, ROLL DESC;

	IS NULL TO CHECK IF A VALUE IS NULL

	UPDATE 

	UPDATE CAPE
	SET GENDER = 'F'
	WHERE COURSE IN ('GAMING', 'AI');

	DELETE FROM CAPE WHERE DOB IS NULL;



*/

SELECT * FROM CAPE;

DELETE FROM CAPE WHERE DOB IS NULL;

SELECT * FROM CAPE;











